export const techcourses = [
  {
    id: 1,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 2,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 3,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 4,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const marketincourses = [
  {
    id: 5,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Marketing Basics",
    author: "Dev Gadhvi",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 6,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Advertisement Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 7,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "The Mood of the Market",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 8,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Market Analysis",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const buisnesscourses = [
  {
    id: 9,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 10,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 11,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 12,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const allCourses = [
  {
    id: 1,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 2,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 3,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 4,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 5,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Marketing Basics",
    author: "Dev Gadhvi",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 6,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Advertisement Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 7,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "The Mood of the Market",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 8,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Market Analysis",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 9,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 10,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 11,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 12,
    src: "https://ik.imagekit.io/princeSherwa/Personal/course.jpg",
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const blogs = [
  {
    id: 1,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 2,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 3,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 4,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 5,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 6,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 7,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 8,
    src: "https://ik.imagekit.io/princeSherwa/Personal/blog.jpg?updatedAt=1714812128464",
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
];
