import course from "../../assets/course.jpg";
import blog from "../../assets/blog.jpg";

export const techcourses = [
  {
    id: 1,
    src: course,
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 2,
    src: course,
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 3,
    src: course,
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 4,
    src: course,
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const marketincourses = [
  {
    id: 5,
    src: course,
    title: "Marketing Basics",
    author: "Dev Gadhvi",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 6,
    src: course,
    title: "Advertisement Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 7,
    src: course,
    title: "The Mood of the Market",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 8,
    src: course,
    title: "Market Analysis",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const buisnesscourses = [
  {
    id: 9,
    src: course,
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 10,
    src: course,
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 11,
    src: course,
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 12,
    src: course,
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const allCourses = [
  {
    id: 1,
    src: course,
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 2,
    src: course,
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 3,
    src: course,
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 4,
    src: course,
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 5,
    src: course,
    title: "Marketing Basics",
    author: "Dev Gadhvi",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 6,
    src: course,
    title: "Advertisement Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 7,
    src: course,
    title: "The Mood of the Market",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 8,
    src: course,
    title: "Market Analysis",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 9,
    src: course,
    title: "React Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 10,
    src: course,
    title: "Javascript Basics",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 11,
    src: course,
    title: "Data Science with Python",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
  {
    id: 12,
    src: course,
    title: "Data Structures",
    author: "Rahul Sharma",
    description: "Best in class React course at discount",
    price: "12999",
  },
];

export const blogs = [
  {
    id: 1,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 2,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 3,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 4,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 5,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 6,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 7,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
  {
    id: 8,
    src: blog,
    title: "The future of Drone Development",
    description: "Lorem ipsum dolor sit amet, socrates amithab, sancro",
  },
];
